services:
  postgres-stockmanager:
    image: postgres:16
    container_name: postgres-stockmanager
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stockmanager_db
      POSTGRES_HOST_AUTH_METHOD: trust  # permet l'accès depuis localhost sans problème
    ports:
      - "5433:5432"  # mappe le port du conteneur vers Windows
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
